// <auto-generated />
namespace Babble.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addingcategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingcategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201901080153038_Adding-categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
